apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scheduler
      name: scheduler
    spec:
      containers:
        - name: scheduler
          # command: ["/bin/sh"]
          image: gcr.io/my-gcp-project-239900/hightower-scheduler:2.0
        - name: kubectl
          image: lachlanevenson/k8s-kubectl
          args:
            - "proxy"
